### ISSUE TITLE
images-cleaner not working?

### ISSUE THREAD

**Issue by mschmidtBP** [meleu/share#13]
Hi,

yesterday I found those great scripts and already used the first one (gamelist-cleaner) to clean up my lists. After some time learning the script, it worked like a charm! I did send you some beer money ;)

sadly the images-cleaner does not want to work at all. No matter what I send in, he always tries to use the files in the image folder as systems ... what doesn't work at all...

So I get messages like:
Working on system: Boomer's Adventure in ASMIK World (USA).mp4
stat: cannot stat "/home/pi/RetroPie/roms/gb/snap/Boomer's": No such file or directory
ERROR: Could not find gamelist for system Boomer's Adventure in ASMIK World (USA).mp4 at location "/home/pi/RetroPie/roms/test"

my gamelist.xml are inside the rom folders and not in the .emulationstation folders. my images are in snap & wheel inside the rom folder.

Is there any way to still use this script?
I am fully okay with running it for every single gamefile by hand, but it refuses to accept a single gamelist.xml as input file and tries to use every file it sees near the gamelist.xml...

**Comment by meleu** [comment]
Hi dude, thanks for the :beer: !

The `images-cleaner.sh` script was created with a very basic setup from the early days of RetroPie.

But I understood your problem and I've just made some changes in order to make it useful for your needs.

First, update the script:
```sh
./images-cleaner.sh --update
```

Then run it using the `--system` option also with `--images` and `--gamelist`, just like my example below for NES:
```sh
./images-cleaner.sh -t --system nes --gamelist ~/RetroPie/roms/nes/ --images ~/RetroPie/roms/nes/wheel
```

**Note**: it's always a good practice to run with the `-t` for the first time (just like I did above), so the script do NOT actually delete any image file. If you are happy with the results, then run it again without the `-t` option.

I'm closing this issue cause it seems solved to me, but feel free to reopen if you think it's still a problem.

Cheers!

**Comment by mschmidtBP** [comment]
Thanks Pal,
I added another beer on my tab for you!

Von: meleu <notifications@github.com>
Gesendet: Montag, 21. Oktober 2019 16:03
An: meleu/share <share@noreply.github.com>
Cc: Marek Schmidt <xxxx@xxxx.net>; Author <author@noreply.github.com>
Betreff: Re: [meleu/share] images-cleaner not working? (#13)


Hi dude, thanks for the 🍺 !

The images-cleaner.sh script was created with a very basic setup from the early days of RetroPie.

But I understood your problem and I've just made some changes in order to make it useful for your needs.

First, update the script:

./images-cleaner.sh --update

Then run it using the --system option also with --images and --gamelist, just like my example below for NES:

./images-cleaner.sh -t --system nes --gamelist ~/RetroPie/roms/nes/ --images ~/RetroPie/roms/nes/wheel

Note: it's always a good practice to run with the -t for the first time (just like I did above), so the script do NOT actually delete any image file. If you are happy with the results, then run it again without the -t option.

I'm closing this issue cause it seems solved to me, but feel free to reopen if you think it's still a problem.

Cheers!
